Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importar el m√≥dulo
import re

# Definir una cadena
X = "abc 123 #&@ 789"

# Compilar el patr√≥n definiendo un grupo
result = re.findall(r"(\d+)", X)

# Recuperar el patr√≥n
print(f"Resultado de \'(\d+)\¬¥: {result}")

# Compilar el patr√≥n definiendo un grupo
result2 = re.findall(r"\w+ (\d+)", X, end="\n"*2)

# Recuperar el patr√≥n
print(f"Resultado de \'\w+ (\d+)\¬¥: {result2}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 14>[0;34m()[0m
[1;32m     11[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mResultado de [39m[38;5;130;01m\'[39;00m[38;5;124m([39m[38;5;124m\[39m[38;5;124md+)[39m[38;5;124m\[39m[38;5;124m¬¥: [39m[38;5;132;01m{[39;00mresult[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     13[0m [38;5;66;03m# Compilar el patr√≥n definiendo un grupo[39;00m
[0;32m---> 14[0m result2 [38;5;241m=[39m [43mre[49m[38;5;241;43m.[39;49m[43mfindall[49m[43m([49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[38;5;124;43m\[39;49m[38;5;124;43mw+ ([39;49m[38;5;124;43m\[39;49m[38;5;124;43md+)[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mX[49m[43m,[49m[43m [49m[43mend[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m"[39;49m[38;5;241;43m*[39;49m[38;5;241;43m2[39;49m[43m)[49m
[1;32m     16[0m [38;5;66;03m# Recuperar el patr√≥n[39;00m
[1;32m     17[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mResultado de [39m[38;5;130;01m\'[39;00m[38;5;124m\[39m[38;5;124mw+ ([39m[38;5;124m\[39m[38;5;124md+)[39m[38;5;124m\[39m[38;5;124m¬¥: [39m[38;5;132;01m{[39;00mresult2[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mTypeError[0m: findall() got an unexpected keyword argument 'end'
TypeError: findall() got an unexpected keyword argument 'end'

